import { MuscleGroup, Exercise, WorkoutLog } from '@/types/database';

export const DEMO_MUSCLE_GROUPS: MuscleGroup[] = [
  {
    id: 'demo-chest',
    name: 'Ngực',
    color: '#FF6B6B',
    target_sets_per_week: 12,
    target_sets_per_month: 48,
    image_uri: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-back',
    name: 'Lưng',
    color: '#4ECDC4',
    target_sets_per_week: 12,
    target_sets_per_month: 48,
    image_uri: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-legs',
    name: 'Chân',
    color: '#95E1D3',
    target_sets_per_week: 10,
    target_sets_per_month: 40,
    image_uri: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-shoulders',
    name: 'Vai',
    color: '#F38181',
    target_sets_per_week: 10,
    target_sets_per_month: 40,
    image_uri: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
];

export const DEMO_EXERCISES: Exercise[] = [
  {
    id: 'demo-bench-press',
    muscle_group_id: 'demo-chest',
    name: 'Bench Press',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-incline-press',
    muscle_group_id: 'demo-chest',
    name: 'Incline Press',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-barbell-row',
    muscle_group_id: 'demo-back',
    name: 'Barbell Row',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-pull-up',
    muscle_group_id: 'demo-back',
    name: 'Pull-up',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-squat',
    muscle_group_id: 'demo-legs',
    name: 'Squat',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-deadlift',
    muscle_group_id: 'demo-legs',
    name: 'Deadlift',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-shoulder-press',
    muscle_group_id: 'demo-shoulders',
    name: 'Shoulder Press',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-lateral-raise',
    muscle_group_id: 'demo-shoulders',
    name: 'Lateral Raise',
    notes: null,
    image_uri: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
];

export const DEMO_WORKOUT_LOGS: WorkoutLog[] = [
  {
    id: 'demo-log-1',
    exercise_id: 'demo-bench-press',
    muscle_group_id: 'demo-chest',
    sets: 4,
    reps: 8,
    weight: 100,
    note: 'Tốt',
    logged_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-log-2',
    exercise_id: 'demo-incline-press',
    muscle_group_id: 'demo-chest',
    sets: 3,
    reps: 10,
    weight: 80,
    note: 'Dễ',
    logged_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-log-3',
    exercise_id: 'demo-barbell-row',
    muscle_group_id: 'demo-back',
    sets: 4,
    reps: 6,
    weight: 120,
    note: 'Khó',
    logged_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
  {
    id: 'demo-log-4',
    exercise_id: 'demo-squat',
    muscle_group_id: 'demo-legs',
    sets: 4,
    reps: 8,
    weight: 140,
    note: 'Tốt',
    logged_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    sync_status: 'synced',
    deleted_at: null,
    user_id: 'demo-user',
  },
];
